services:
 postgresql:
  image: postgres
  environment:
   POSTGRES_PASSWORD: "faketory"
  ports:
   - "5432:5432"
 faketory-api:
  build:
   context: .
   dockerfile: Faketory.API/Dockerfile
  ports:
   - "8080:80"
  depends_on:
  - postgresql