// <auto-generated />
using System;
using Faketory.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Faketory.Infrastructure.Migrations
{
    [DbContext(typeof(FaketoryDbContext))]
    [Migration("20220720181521_machines-added")]
    partial class machinesadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Faketory.Domain.Resources.IndustrialParts.Conveyor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<Guid>("IOId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTurnedDownOrLeft")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVertical")
                        .HasColumnType("boolean");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<bool>("NegativeLogic")
                        .HasColumnType("boolean");

                    b.Property<int>("PosX")
                        .HasColumnType("integer");

                    b.Property<int>("PosY")
                        .HasColumnType("integer");

                    b.Property<int>("Ticks")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IOId");

                    b.ToTable("Conveyors");
                });

            modelBuilder.Entity("Faketory.Domain.Resources.IndustrialParts.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastProcessedPalletId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PalletAlreadyProcessed")
                        .HasColumnType("boolean");

                    b.Property<int>("PosX")
                        .HasColumnType("integer");

                    b.Property<int>("PosY")
                        .HasColumnType("integer");

                    b.Property<int>("ProcessingTimestampAmount")
                        .HasColumnType("integer");

                    b.Property<int>("RandomFactor")
                        .HasColumnType("integer");

                    b.Property<int>("Ticks")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Faketory.Domain.Resources.IndustrialParts.Pallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("PosX")
                        .HasColumnType("integer");

                    b.Property<int>("PosY")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pallets");
                });

            modelBuilder.Entity("Faketory.Domain.Resources.IndustrialParts.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IOId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSensing")
                        .HasColumnType("boolean");

                    b.Property<bool>("NegativeLogic")
                        .HasColumnType("boolean");

                    b.Property<int>("PosX")
                        .HasColumnType("integer");

                    b.Property<int>("PosY")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IOId");

                    b.ToTable("Sensor");
                });

            modelBuilder.Entity("Faketory.Domain.Resources.PLCRelated.IO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Bit")
                        .HasColumnType("integer");

                    b.Property<int>("Byte")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SlotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SlotId");

                    b.ToTable("InputsOutputs");
                });

            modelBuilder.Entity("Faketory.Domain.Resources.PLCRelated.PlcEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Plcs");
                });

            modelBuilder.Entity("Faketory.Domain.Resources.PLCRelated.PlcModel", b =>
                {
                    b.Property<int>("CpuModel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Cpu")
                        .HasColumnType("integer");

                    b.Property<short>("Rack")
                        .HasColumnType("smallint");

                    b.Property<short>("Slot")
                        .HasColumnType("smallint");

                    b.HasKey("CpuModel");

                    b.ToTable("PlcModels");

                    b.HasData(
                        new
                        {
                            CpuModel = 1200,
                            Cpu = 30,
                            Rack = (short)0,
                            Slot = (short)1
                        },
                        new
                        {
                            CpuModel = 1500,
                            Cpu = 40,
                            Rack = (short)0,
                            Slot = (short)1
                        },
                        new
                        {
                            CpuModel = 300,
                            Cpu = 10,
                            Rack = (short)0,
                            Slot = (short)2
                        },
                        new
                        {
                            CpuModel = 400,
                            Cpu = 20,
                            Rack = (short)0,
                            Slot = (short)2
                        });
                });

            modelBuilder.Entity("Faketory.Domain.Resources.PLCRelated.Slot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PlcId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlcId")
                        .IsUnique();

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("Faketory.Domain.Resources.PLCRelated.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.HasKey("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Faketory.Domain.Resources.IndustrialParts.Conveyor", b =>
                {
                    b.HasOne("Faketory.Domain.Resources.PLCRelated.IO", "IO")
                        .WithMany()
                        .HasForeignKey("IOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IO");
                });

            modelBuilder.Entity("Faketory.Domain.Resources.IndustrialParts.Sensor", b =>
                {
                    b.HasOne("Faketory.Domain.Resources.PLCRelated.IO", "IO")
                        .WithMany()
                        .HasForeignKey("IOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IO");
                });

            modelBuilder.Entity("Faketory.Domain.Resources.PLCRelated.IO", b =>
                {
                    b.HasOne("Faketory.Domain.Resources.PLCRelated.Slot", null)
                        .WithMany("InputsOutputs")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Faketory.Domain.Resources.PLCRelated.PlcEntity", b =>
                {
                    b.HasOne("Faketory.Domain.Resources.PLCRelated.PlcModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Faketory.Domain.Resources.PLCRelated.Slot", b =>
                {
                    b.HasOne("Faketory.Domain.Resources.PLCRelated.PlcEntity", "Plc")
                        .WithOne()
                        .HasForeignKey("Faketory.Domain.Resources.PLCRelated.Slot", "PlcId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Plc");
                });

            modelBuilder.Entity("Faketory.Domain.Resources.PLCRelated.Slot", b =>
                {
                    b.Navigation("InputsOutputs");
                });
#pragma warning restore 612, 618
        }
    }
}
